import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/ui/header";
import { Toaster } from "@/components/ui/toaster";
import { cookies } from "next/headers";
import AppProvider from "@/app/AppProvider";
import HeaderLayout from "@/app/header";
import HeaderSession from "@/components/ui/header-session";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "300"] });

export const metadata: Metadata = {
  title: "Blog App",
  description: "Generated by huuloc2026",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const sessionToken = cookieStore.get("sessionToken");
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={roboto.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* <Header /> */}
          <>{ sessionToken ? <HeaderSession /> : <Header />}</>
          <AppProvider initialSessionToken={sessionToken?.value || ""}> 
            <Toaster />
            {children}
          </AppProvider>
        </ThemeProvider>
      </body>
    </html>
  );
} 
